version: '3'

services:
  frontend:
    image: frontend-image-id
    container_name: save-test-front
    command: serve -s build -l 3000
    stdin_open: true
    tty: true
    environment:
        - PORT=3000

  nginx:
    image: nginx-image-id
    container_name: save-test-nginx
    volumes:
        - ./volumes/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    ports:
      - 4580:80

